# Generated by Django 6.0.4 on 2026-05-16 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0007_product_low_stock_threshold_sale_discount_amount_and_more'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gold_type', models.CharField(help_text='e.g., Broken Ring, Scrap, Coin', max_length=100)),
                ('karat', models.IntegerField(choices=[(18, '18K'), (21, '21K'), (22, '22K'), (24, '24K')])),
                ('estimated_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='online_purchases/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('offered', 'Offer Sent'), ('accepted', 'Accepted'), ('item_received', 'Item Received'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('shop_offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='branch',
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.product'),
        ),
    ]
